name: Upload iOS App to App Store

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    # 上传到 App Store
    - name: Upload to App Store using altool
      env:
        IPA_PATH: "ios/HoneyAI.ipa"
        APPLE_ID: "pjmmh6jbh@hotmail.com"
        APP_SPECIFIC_PASSWORD: "jjpl-sliy-dcxy-kgus"
      run: |
        xcrun altool --upload-app -f "$IPA_PATH" \
          -t ios \
          -u "$APPLE_ID" \
          -p "$APP_SPECIFIC_PASSWORD" \
          --verbose



